### ISSUE TITLE
Flattened struct fields hide unused items

### ISSUE THREAD

**Issue by JoelScarfone** [dtolnay/serde-ignored#14]
If a struct's field is "flattened" with the macro `#[serde(flatten)]`, ignored elements when deserializing are not discovered. Here is a minimal reproduction where there is clearly an unused element but because the field is flattened, `serde-ignored` does not find that it is ignored. Removing `#[serde(flatten)]` and adding "[inner]" into the start of the raw text we are attempting to deserialize works fine, and the unused field is identified.

```
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug)]
struct MyStruct {
    #[serde(flatten)]
    inner: Inner,
}

#[derive(Serialize, Deserialize, Debug)]
struct Inner {
    working: bool,
}

fn main() {
    let raw = r"
    working = true
    unused = 'yes'
    ";

    let mut d = toml::de::Deserializer::new(raw);

    let mut unused = vec![];
    let example: MyStruct = serde_ignored::deserialize(&mut d, |path| {
        unused.push(path.to_string());
    }).unwrap();

    println!("{:?}\n\n{:?}", example, unused);
}
```

**Comment by brianc118** [comment]
Just hit this too: looks to be the same as #10

**Comment by JoelScarfone** [comment]
Ahh, thanks @brianc118 for pointing out the clone. I'll close this as it is for sure tracked there.
