### ISSUE TITLE
Fields inside untagged enum

### ISSUE THREAD

**Issue by ctaggart** [dtolnay/serde-ignored#9]
--  ❤️  --> Serde is amazing! Thank you for making it.

I wrote an [assert_deserialized_without_ignored](https://github.com/ctaggart/autorust_openapi/blob/f21d16e291fd46e956216a04f61d7d3b29ba087a/tests/common/mod.rs#L9-L24), hoping that it would catch anything that is ignored, but it misses many items. Did I misunderstand something?

``` rust
pub fn assert_deserialize_without_ignored<P: AsRef<Path> + std::fmt::Debug>(paths: Vec<P>) -> Result<()> {
    for path in paths {
        println!("  test {:?}", path);
        let mut bytes = Vec::new();
        File::open(path)?.read_to_end(&mut bytes)?;
        let deserializer = &mut serde_json::Deserializer::from_slice(&bytes);
        let mut ignored = Vec::new();
        let _spec: OpenAPI = serde_ignored::deserialize(deserializer, |path| {
            let path = path.to_string();
            println!("    ignored {}", &path);
            ignored.push(path);
        })?;
        assert_eq!(0, ignored.len());
    }
    Ok(())
}
```

See https://github.com/ctaggart/autorust_openapi/issues/3#issuecomment-698976633 for a specific case about `x-nullable` not showing up as ignored for https://github.com/Azure/azure-rest-api-specs/blob/master/specification/batch/data-plane/Microsoft.Batch/stable/2020-09-01.12.0/BatchService.json.

**Comment by dtolnay** [comment]
You have x-nullable inside something that is being deserialized as [ReferenceOr](https://github.com/ctaggart/autorust_openapi/blob/f21d16e291fd46e956216a04f61d7d3b29ba087a/src/reference.rs). The untagged enum is equivalent to deserializing everything in the object to a format-independent variation of serde_json::Value and sequentially attempting to deserialize the Value to each possible untagged variant.

It looks like you are expecting to identify ReferenceOr::Reference based on presence of a $ref field. If $ref is guaranteed to be first field, you can write a Deserialize impl which looks for it as the first field to decide whether to deserialize as Reference or Item. If it is not guaranteed to be the first field, there is no way you can avoid deserializing previous fields while looking for $ref, including fields that you don't end up putting into ReferenceOr::Item after not finding a $ref.

**Comment by ctaggart** [comment]
Thank you for digging into it and the explanation. 💟  You renamed this the issue title, so I assume you wish to keep it open.
